config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  resources :pdf_documents, only: [:index, :new, :create]
  root 'pdf_documents#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pdf_documento.rb
class PdfDocumento < ApplicationRecord
  mount_uploader :file_path, PdfUploader

  before_save :extract_pdf_info

  private

  def extract_pdf_info
    if file_path.present? && file_path.file.exists?
      reader = PDF::Reader.new(file_path.file.path)
      self.file_size = File.size(file_path.file.path)
      self.num_pages = reader.pages.size
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pdf_documentos_controller.rb
class PdfDocumentosController < ApplicationController
  def index
    @pdf_documento = PdfDocumento.all
  end

  def new

    @pdf_documento = PdfDocumento.new
  end

  def create

    @pdf_documento = PdfDocumento.new(pdf_documento_params)
    if @pdf_documento.save
      redirect_to pdf_documento_path, notice: 'Documento enviado com sucesso.'
    else
      render :new
    end
  end

  private

  def pdf_documento_params
    params.require(:pdf_document).permit(:title, :author, :creation_date, :file_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebTechProva</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pdf_documentos/index.html.erb
<!-- app/views/pdf_documents/index.html.erb -->
<h1>Lista de Documentos PDF</h1>

<%= link_to 'Novo Documento', new_pdf_document_path, class: 'btn btn-primary' %>

<% @pdf_documents.each do |pdf_document| %>
  <div>
    <h3><%= pdf_document.title %></h3>
    <p>Autor: <%= pdf_document.author %></p>
    <p>Data de Criação: <%= pdf_document.creation_date %></p>
    <%= link_to 'Visualizar', pdf_document, class: 'btn btn-secondary' %>
  </div>
<% end %>